### PR TITLE
Optimize motion timeout transmission

### LINKED ISSUE #1065: [Bug] Interconnect High Retry Counts During TPC-DS 100GB Execution with 4 Concurrent Users
### Apache Cloudberry version

main branch, commit:1cbab9b3

### What happened

psql:q67.sql:46: WARNING:  interconnect may encountered a network error, please check your network  (seg72 slice6 10.13.8.103:9000 pid=2229356)
DETAIL:  Failing to send packet (seq 1) to 10.13.8.102:55905 (pid 1668328 cid 70) after 100 retries.
psql:q67.sql:46: WARNING:  interconnect may encountered a network error, please check your network  (seg74 slice6 10.13.8.103:9002 pid=2229359)
DETAIL:  Failing to send packet (seq 1) to 10.13.8.100:24440 (pid 3218409 cid 17) after 100 retries.
psql:q67.sql:46: WARNING:  interconnect may encountered a network error, please check your network  (seg73 slice7 10.13.8.103:9001 pid=2229548)
DETAIL:  Failing to send packet (seq 1) to 10.13.8.102:24287 (pid 1668320 cid 62) after 100 retries.
psql:q67.sql:46: WARNING:  interconnect may encountered a network error, please check your network  (seg64 slice5 10.13.8.102:9016 pid=1668898)
DETAIL:  Failing to send packet (seq 1) to 10.13.8.101:17582 (pid 1698993 cid 28) after 100 retries.
psql:q67.sql:46: WARNING:  interconnect may encountered a network error, please check your network  (seg31 slice4 10.13.8.101:9007 pid=1699404)
DETAIL:  Failing to send packet (seq 1) to 10.13.8.102:62775 (pid 1668295 cid 50) after 100 retries.

### What you think should happen instead

_No response_

### How to reproduce

Generate 100GB of data by setting GEN_DATA_SCALE="100" in the TPC-DS variables.

Download the scripts provided below. Ensure that the role and schema in the search_path in q67.sql match the settings used when generating the TPC-DS data.
[test.zip](https://github.com/user-attachments/files/19905085/test.zip)

Run sh test.sh to initiate the test.

### Operating System

Oracle Linux 9.5

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/cloudberry/blob/main/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by oracleloyall**
The primary goal is to address various issues currently encountered during concurrent processes,
such as excessive motion retries, congestion, retransmission storms, and network skew.
The code addresses inefficient network retransmission handling in unreliable network environments. Specifically:

Fixed Timeout Thresholds: Traditional TCP-style Retransmission Timeout (RTTVAR.RTO) calculations may be too rigid for networks with volatile latency (e.g., satellite links, wireless networks). This leads to: • Premature Retransmissions: Unnecessary data resends during temporary latency spikes, wasting bandwidth.
• Delayed Recovery: Slow reaction to actual packet loss when RTO is overly conservative.

Lack of Context Awareness: Static RTO ignores real-time network behavior patterns, reducing throughput and responsiveness.

Solution: Dynamic Timeout Threshold Adjustment
Implements an adaptive timeout mechanism to optimize retransmission: if (now < (curBuf->sentTime + conn->rttvar.rto)) { uint32_t diff = (curBuf->sentTime + conn->rttvar.rto) - now; // ... (statistical tracking and threshold adjustment) }

Key Components:
• Statistical Tracking:
\- min/max: Tracks observed minimum/maximum residual time (time left until RTO expiry).
\- retrans_count/no_retrans_count: Counts retransmission vs. non-retransmission events.

• Weighted Threshold Calculation:
unack_queue_ring.time_difference = (uint32_t)(
unack_queue_ring.max * weight_no_retrans +
unack_queue_ring.min * weight_retrans
);
Weights derived from historical ratios of retransmissions (weight_retrans) vs. successful deliveries (weight_no_retrans).

How It Solves the Problem:
• Temporary Latency Spike: Uses max (conservative) to avoid false retransmits, reducing bandwidth waste (vs. traditional mistaken retransmissions).
• Persistent Packet Loss: Prioritizes min (aggressive) via weight_retrans, accelerating recovery (vs. slow fixed-RTO reaction). • Stable Network: Balances weights for equilibrium throughput (vs. static RTO limitations).

EstimateRTT - Dynamically estimates the Round-Trip Time (RTT) and adjusts Retransmission Timeout (RTO)

This function implements a variant of the Jacobson/Karels algorithm for RTT estimation, adapted for UDP-based motion control connections. It updates smoothed RTT (srtt), mean deviation (mdev), and RTO values based on newly measured RTT samples (mrtt). The RTO calculation ensures reliable data transmission over unreliable networks.

Key Components:

* srtt:   Smoothed Round-Trip Time (weighted average of historical RTT samples)
* mdev:   Mean Deviation (measure of RTT variability)
* rttvar: Adaptive RTT variation bound (used to clamp RTO updates)
* rto:    Retransmission Timeout (dynamically adjusted based on srtt + rttvar)

Algorithm Details:

1. For the first RTT sample:
   srtt    = mrtt << 3   (scaled by 8 for fixed-point arithmetic)
   mdev    = mrtt << 1   (scaled by 2)
   rttvar  = max(mdev, rto_min)
2. For subsequent samples:
   Delta   = mrtt - (srtt >> 3)  (difference between new sample and smoothed RTT)
   srtt   += Delta               (update srtt with 1/8 weight of new sample)
   Delta   = abs(Delta) - (mdev >> 2)
   mdev   += Delta               (update mdev with 1/4 weight)
3. rttvar bounds the maximum RTT variation:
   If mdev > mdev_max, update mdev_max and rttvar
   On new ACKs (snd_una > rtt_seq), decay rttvar toward mdev\_max
4. Final RTO calculation:
   rto = (srtt >> 3) + rttvar   (clamped to RTO_MAX)

Network Latency Filtering and RTO Optimization

This logic mitigates RTO distortion caused by non-network delays in database execution pipelines. Key challenges addressed:

* Operator processing delays (non-I/O wait) inflate observed ACK times
* Spurious latency amplification in lossy networks triggers excessive RTO_MAX waits
* Congestion collapse from synchronized retransmissions

Core Mechanisms:

1. Valid RTT Sampling Filter: Condition: 4 * (pkt->recv_time - pkt->send_time) > ackTime && pkt->retry_times != Gp_interconnect_min_retries_before_timeout Rationale:

   * Filters packets exceeding 2x expected round-trips (4x one-way)
   * Excludes artificial retries (retry_times=Gp_interconnect_min_retries_before_timeout) to avoid sampling bias Action: Update RTT estimation only with valid samples via EstimateRTT()

2. Randomized Backoff: Condition: buf->nRetry > 0 Algorithm: rto += (rto >> (4 * buf->nRetry)) Benefits:

   * Exponential decay: Shifts create geometrically decreasing increments
   * Connection-specific randomization: Prevents global synchronization
   * Dynamic scaling: Adapts to retry depth (nRetry)

3. Timer List Management (NEW_TIMER): Operations: RemoveFromRTOList(&mudp, bufConn) → Detaches from monitoring
   AddtoRTOList(\&mudp, bufConn)       → Reinserts with updated rto
   Purpose: Maintains real-time ordering of expiration checks

We conducted multiple full-scale TPCDS benchmarks using both a single physical machine with 48 nodes and four physical machines with 96 nodes, testing with MTU values of 1500 and 9000. In the single-node environment with no network bottlenecks, there were no significant performance differences between using MTU 1500 and 9000. In the 96-node environment, under single-threaded execution, there were no significant performance differences. However, under multi-threaded execution (4 threads), SQL statements with a high percentage of data movement showed significant performance variations, ranging from 5 to 10 times, especially with MTU 1500.

Fixes #1065

### What does this PR do?

The primary goal is to address various issues currently encountered during concurrent processes, such as excessive motion retries, congestion, retransmission storms, and network skew. The code addresses inefficient network retransmission handling in unreliable network environments.
### Type of Change
- [x] Bug fix (non-breaking change)
- [x] New feature (non-breaking change)
- [ ] Breaking change (fix or feature with breaking changes)
- [ ] Documentation update

### Test Plan

- [x] Unit tests added/updated
- [x] Integration tests added/updated
- [x] Passed `make installcheck`
- [x] Passed `make -C src/test installcheck-cbdb-parallel`

### Impact

**Performance:**

**User-facing changes:**

**Dependencies:**

### Checklist
- [ ] Followed [contribution guide](https://cloudberry.apache.org/contribute/code)
- [ ] Added/updated documentation
- [ ] Reviewed code for security implications
- [ ] Requested review from [cloudberry committers](https://github.com/orgs/apache/teams/cloudberry-committers)

### CI Skip Instructions

---

### CODE REVIEW

**Comment by oracleloyall** [comment]
```
Test tpcds(1000G) results for 4 concurrent connections and 96 nodes
| Query ID | (MTU 1500) Optimized motion execution time | Origin motion execution time | Improvement ratio |
|----------|---------------------------|----------------------|-------------|
| 101      | 8                         | 8                    | 1           |
| 102      | 38                        | 39                   | 1.026315789 |
| 103      | 16                        | 16                   | 1           |
| 104      | 196                       | 1430                 | 7.295918367 |
| 105      | 49                        | 49                   | 1           |
| 106      | 16                        | 16                   | 1           |
| 107      | 27                        | 27                   | 1           |
| 108      | 19                        | 21                   | 1.105263158 |
| 109      | 108                       | 108                  | 1           |
| 110      | 29                        | 29                   | 1           |
| 111      | 112                       | 817                  | 7.294642857 |
| 112      | 5                         | 5                    | 1           |
| 113      | 29                        | 29                   | 1           |
| 114      | 298                       | 300                  | 1.006711409 |
| 115      | 11                        | 10                   | 0.909090909 |
| 116      | 44                        | 1803                 | 40.97727273 |
| 117      | 33                        | 33                   | 1           |
| 118      | 37                        | 27                   | 0.72972973  |
| 119      | 21                        | 21                   | 1           |
| 120      | 8                         | 8                    | 1           |
| 121      | 6                         | 6                    | 1           |
| 122      | 13                        | 13                   | 1           |
| 123      | 1442                      | 18600                | 12.89875173 |
| 124      | 312                       | 7613                 | 24.40064103 |
| 125      | 33                        | 68                   | 2.060606061 |
| 126      | 15                        | 19                   | 1.266666667 |
| 127      | 26                        | 28                   | 1.076923077 |
| 128      | 59                        | 58                   | 0.983050847 |
| 129      | 33                        | 32                   | 0.96969697  |
| 130      | 12                        | 3                    | 0.25        |
| 131      | 36                        | 37                   | 1.027777778 |
| 132      | 16                        | 15                   | 0.9375      |
| 133      | 36                        | 36                   | 1           |
| 134      | 22                        | 22                   | 1           |
| 135      | 43                        | 37                   | 0.860465116 |
| 136      | 31                        | 31                   | 1           |
| 137      | 6                         | 6                    | 1           |
| 138      | 68                        | 745                  | 10.95588235 |
| 139      | 10                        | 10                   | 1           |
| 140      | 10                        | 11                   | 1.1         |
| 141      | 1                         | 0                    | 0           |
| 142      | 16                        | 16                   | 1           |
| 143      | 22                        | 22                   | 1           |
| 144      | 27                        | 27                   | 1           |
| 145      | 7                         | 8                    | 1.142857143 |
| 146      | 30                        | 29                   | 0.966666667 |
| 147      | 38                        | 38                   | 1           |
| 148      | 33                        | 33                   | 1           |
| 149      | 39                        | 39                   | 1           |
| 150      | 23                        | 24                   | 1.043478261 |
| 151      | 36                        | 37                   | 1.027777778 |
| 152      | 16                        | 16                   | 1           |
| 153      | 19                        | 19                   | 1           |
| 154      | 36                        | 31                   | 0.861111111 |
| 155      | 16                        | 16                   | 1           |
| 156      | 31                        | 31                   | 1           |
| 157      | 21                        | 21                   | 1           |
| 158      | 28                        | 28                   | 1           |
| 159      | 95                        | 96                   | 1.010526316 |
| 160      | 39                        | 39                   | 1           |
| 161      | 42                        | 42                   | 1           |
| 162      | 10                        | 10                   | 1           |
| 163      | 19                        | 19                   | 1           |
| 164      | 57                        | 54                   | 0.947368421 |
| 165      | 53                        | 53                   | 1           |
| 166      | 20                        | 20                   | 1           |
| 167      | 560                       | 3843                 | 6.8625      |
| 168      | 28                        | 28                   | 1           |
| 169      | 28                        | 28                   | 1           |
| 170      | 54                        | 54                   | 1           |
| 171      | 31                        | 30                   | 0.967741935 |
| 172      | 281                       | 307                  | 1.09252669  |
| 173      | 20                        | 21                   | 1.05        |
| 174      | 79                        | 733                  | 9.278481013 |
| 175      | 72                        | 66                   | 0.916666667 |
| 176      | 16                        | 16                   | 1           |
| 177      | 35                        | 35                   | 1           |
| 178      | 157                       | 167                  | 1.063694268 |
| 179      | 28                        | 27                   | 0.964285714 |
| 180      | 45                        | 44                   | 0.977777778 |
| 181      | 11                        | 7                    | 0.636363636 |
| 182      | 9                         | 9                    | 1           |
| 183      | 5                         | 5                    | 1           |
| 184      | 14                        | 6                    | 0.428571429 |
| 185      | 13                        | 13                   | 1           |
| 186      | 9                         | 10                   | 1.111111111 |
| 187      | 68                        | 513                  | 7.544117647 |
| 188      | 131                       | 130                  | 0.992366412 |
| 189      | 20                        | 20                   | 1           |
| 190      | 9                         | 9                    | 1           |
| 191      | 2                         | 3                    | 1.5         |
| 192      | 8                         | 8                    | 1           |
| 193      | 23                        | 24                   | 1.043478261 |
| 194      | 22                        | 561                  | 25.5        |
| 195      | 189                       | 1155                 | 6.111111111 |
| 196      | 16                        | 17                   | 1.0625      |
| 197      | 42                        | 41                   | 0.976190476 |
| 198      | 16                        | 17                   | 1.0625      |
| 199      | 19                        | 18                   | 0.947368421 |
|          | 6167                      | 40919                | 6.635154856 |
```

**Comment by zhangyue1818** [comment]
add a suitable commit title pls.

File: src/backend/utils/misc/guc_gp.c [hunk 1]
```diff
@@ -3759,6 +3761,16 @@ struct config_int ConfigureNamesInt_gp[] =
 		NULL, NULL, NULL
 	},
 
+	{
+		{"gp_interconnect_mem_size", PGC_USERSET, GP_ARRAY_TUNING,
+			gettext_noop("Sets the maximum size of the send/recv queue memory for all connections in the UDP interconnect"),
+			NULL
+		},
+		&Gp_interconnect_mem_size,
+		10, 1, 1024,
```
Comment (zhangyue1818) [inline src/backend/utils/misc/guc_gp.c:3770]: What is the unit of memory size?

File: contrib/interconnect/udp/ic_udpifc.c [hunk 2]
```diff
@@ -116,6 +120,59 @@ WSAPoll(
...
+#define UDP_INITIAL_RTO                 (MSEC_TO_USEC(200))
+#define UDP_DEFAULT_MSS 1460
+
+#define UDP_SEQ_GT(a,b) 		((int32_t)((a)-(b)) > 0)
+
+#define RTO_HASH (3000)
+
+#define UDP_SEQ_LT(a,b) ((int32_t)((a)-(b)) < 0)
+#define UDP_SEQ_LEQ(a,b) ((int32_t)((a)-(b)) <= 0)
+#define UDP_SEQ_GT(a,b) ((int32_t)((a)-(b)) > 0)
```
Comment (zhangyue1818) [inline contrib/interconnect/udp/ic_udpifc.c:143]: Duplicate code

File: contrib/interconnect/udp/ic_udpifc.c [hunk 3]
```diff
@@ -924,6 +993,353 @@ dumpTransProtoStats()
 
 #endif							/* TRANSFER_PROTOCOL_STATS */
 
+static struct rto_hashstore*
+initRTOHashstore()
+{
+	int i;
+	struct rto_hashstore* hs = palloc(sizeof(struct rto_hashstore));
+	if (!hs)
+		return 0;
```
Comment (zhangyue1818) [inline contrib/interconnect/udp/ic_udpifc.c]: not run here if palloc fails.

File: contrib/interconnect/udp/ic_udpifc.c [hunk 4]
```diff
@@ -924,6 +993,353 @@ dumpTransProtoStats()
...
+{
+	MotionConnUDP *walk, *next;
+	struct rto_head* rto_list = &mudp->rto_store->rto_list[RTO_HASH];
+	int cnt = 0;
+
+	for (walk = TAILQ_FIRST(rto_list); walk != NULL; walk = next)
+	{
+		next = TAILQ_NEXT(walk, sndvar.timer_link);
+
+		int diff = (int32_t)(mudp->rto_store->rto_now_ts - walk->sndvar.ts_rto);
```
Comment (zhangyue1818) [inline contrib/interconnect/udp/ic_udpifc.c:1157]: Is int32_t sufficient for diff?

File: contrib/interconnect/udp/ic_udpifc.c [hunk 5]
```diff
@@ -924,6 +993,353 @@ dumpTransProtoStats()
...
+
+	cnt = 0;
+
+	while (1)
+	{
+		rto_list = &mudp->rto_store->rto_list[mudp->rto_store->rto_now_idx];
+		if ((int32_t)(cur_ts - mudp->rto_store->rto_now_ts) < 0)
+			break;
+
+		for (walk = TAILQ_FIRST(rto_list);
```
Comment (zhangyue1818) [inline contrib/interconnect/udp/ic_udpifc.c]: Is it better one line?

File: contrib/interconnect/udp/ic_udpifc.c (hunk 4 above)
Comment (oracleloyall) [reply contrib/interconnect/udp/ic_udpifc.c:1157]: enough

File: src/backend/utils/misc/guc_gp.c (hunk 1 above)
Comment (oracleloyall) [reply src/backend/utils/misc/guc_gp.c:3770]: The unit is Megabyte, and the description information will be added later.

File: contrib/interconnect/udp/ic_udpifc.c [hunk 6]
```diff
@@ -3284,13 +3733,49 @@ static inline void
...
 		 * technically it is not part of current query, discard it directly.
 		 */
 		resetRxThreadError();
+		if (estate != NULL && estate->es_sliceTable != NULL)
+			sliceNum = estate->es_sliceTable->numSlices;
+		else
+			sliceNum = 1;
+
+		if (Gp_interconnect_mem_size > 0 &&
+			Gp_interconnect_queue_depth == 4 &&
```
Comment (zhangyue1818) [inline contrib/interconnect/udp/ic_udpifc.c:3752]: It will not work if the default value of Gp_interconnect_snd_queue_depth or/and Gp_interconnect_queue_depth changes. It's better use the same const macro in guc_gp.c and here.

Comment (oracleloyall) [reply contrib/interconnect/udp/ic_udpifc.c:3752]: When configuring 4 and 2, memory is enabled, regardless of the default

**Review by zhangyue1818 — APPROVED** [review]
