### PR TITLE
fix(backend): Skip interconnect initialization for auxiliary background workers

### LINKED ISSUE #1389: Auxiliary process opens unnecessary network sockets
Data exchange between backend processes uses network sockets. The listener socket is created when the backend process is initialized. However, some auxiliary process doesn't require interconnect for data exchange.
Exposing unnecessary network ports is not a good idea, which may be considered security issue in a higher standard.

### PR DESCRIPTION
**Pull request by zhan7236**
## Summary

This PR addresses Issue #1389 by preventing auxiliary background worker processes from opening unnecessary network sockets during interconnect initialization.

## Problem

Auxiliary background workers (ftsprobe, global deadlock detector, dtx recovery, sweeper, pg_cron launcher, ic proxy) were initializing the Motion Layer IPC, which opens network sockets for data exchange. Since these processes don't require interconnect communication, this behavior is unnecessary and can be considered a security concern.

## Solution

Added a check for `amAuxiliaryBgWorker()` in both `cdb_setup()` and `cdb_cleanup()` functions to skip interconnect initialization and cleanup for auxiliary background workers.

### Changes:
- Modified `src/backend/cdb/cdbutil.c`:
  - Added `!amAuxiliaryBgWorker()` condition to `cdb_setup()` to skip `InitMotionLayerIPC()` call
  - Added `!amAuxiliaryBgWorker()` condition to `cdb_cleanup()` to skip `CleanUpMotionLayerIPC()` call
  - Applied to both `#ifdef USE_INTERNAL_FTS` and `#else` code paths

## Testing

- Code review verified correct syntax and logic
- Header file `postmaster/postmaster.h` already included in cdbutil.c
- Function `amAuxiliaryBgWorker()` properly declared in postmaster.h

Fixes #1389

### CODE REVIEW

File: src/backend/cdb/cdbutil.c [hunk 1]
```diff
@@ -1138,7 +1138,14 @@ cdb_setup(void)
 {
 	elog(DEBUG1, "Initializing Cloudberry components...");
 
-	if (Gp_role != GP_ROLE_UTILITY && !IS_SINGLENODE())
+	/*
```
Comment (my-ship-it) [inline src/backend/cdb/cdbutil.c]: Wouldn't it be better if we don't call the cdb_setup & cdb_cleanup function?

Comment (zhan7236) [reply src/backend/cdb/cdbutil.c]: Makes sense. Updated.

**Comment by tuhaihe** [comment]
Hi @zhan7236 Thank you for your contribution! Your PR has now been merged into the main branch. Congratulations!
