### PR TITLE
ORCA: Fix eliminate self comparison

### LINKED ISSUE #594: [Bug] Error detected by sqlancer
### Cloudberry Database version

_No response_

### What happened

The last two selects should get the same result, but they are not

### What you think should happen instead

_No response_

### How to reproduce

CREATE TABLE IF NOT EXISTS t0(c0 FLOAT  DEFAULT (0.64844320698434) UNIQUE PRIMARY KEY NOT NULL, c1 inet  DEFAULT ('[228.195.152.147](http://228.195.152.147/)') NOT NULL) WITH (autovacuum_vacuum_cost_delay=72);
CREATE TABLE IF NOT EXISTS t1(LIKE t0);
CREATE TABLE t5(LIKE t1);

INSERT INTO t1(c0, c1) VALUES(0.9445783, '[152.175.55.223](http://152.175.55.223/)');

INSERT INTO t0(c1, c0) VALUES('[86.163.150.122](http://86.163.150.122/)', 0.51151264), ('[153.68.173.244](http://153.68.173.244/)', 1.08803891E9), ('[201.139.35.173](http://201.139.35.173/)', 0.032230698);

DELETE FROM ONLY t5 RETURNING + (((+ (abs(-1165130706)))+(CAST(((TRUE)AND(FALSE)) AS INT))));
INSERT INTO t5(c1, c0) VALUES('[66.75.211.162](http://66.75.211.162/)', 0.4240951), ('[10.91.215.127](http://10.91.215.127/)', - (pg_backend_pid())), ('[1.78.54.190](http://1.78.54.190/)', 0.7707819) ON CONFLICT  DO NOTHING;

INSERT INTO t1(c0, c1) VALUES(0.98276824, '[230.228.200.54](http://230.228.200.54/)') ON CONFLICT  DO NOTHING;
INSERT INTO t5(c1, c0) VALUES('[173.7.80.33](http://173.7.80.33/)', 0.5569468);

INSERT INTO t0(c0) VALUES(2.26024944E8);

INSERT INTO t5(c0, c1) VALUES(0.51061195, '[168.211.249.233](http://168.211.249.233/)');

INSERT INTO t5(c0, c1) OVERRIDING USER VALUE VALUES(0.48478556, '[175.136.165.46](http://175.136.165.46/)');
INSERT INTO t0(c0) VALUES(0.9292619);

INSERT INTO t0(c0) VALUES(num_nonnulls(((((1349498262)/(839490868)))*(num_nulls(CAST(0.2903752 AS MONEY), CAST(0.83137906 AS MONEY), '[46.127.254.133](http://46.127.254.133/)', B'1111111111111111111111111111111111101111010101111010101001111111', 1473917725))))), (-9.3304762E8), (0.042748928), (0.5439545), (0.0026354373);

INSERT INTO t1(c1, c0) VALUES('[187.156.97.166](http://187.156.97.166/)', 0.9357929);

INSERT INTO t0(c0) VALUES(0.32275215);
SELECT t1.c0, t1.c1, t5.c0, t5.c1 FROM t1 FULL OUTER JOIN t5 ON (('}n()')LIKE(CAST(((0.7999568)IS DISTINCT FROM(0.53532124)) AS VARCHAR(100)))) WHERE NOT (((t1.c1)>=(t1.c1))) UNION ALL SELECT t1.c0, t1.c1, t5.c0, t5.c1 FROM t1* FULL OUTER JOIN t5* ON (('}n()')LIKE(CAST(((0.7999568)IS DISTINCT FROM(0.53532124)) AS VARCHAR(100)))) WHERE NOT (NOT (((t1.c1)>=(t1.c1)))) UNION ALL SELECT t1.c0, t1.c1, t5.c0, t5.c1 FROM t1* FULL OUTER JOIN t5* ON (('}n()')LIKE((((0.7999568)IS DISTINCT FROM(0.53532124)))::VARCHAR(100))) WHERE (NOT (((t1.c1)>=(t1.c1)))) ISNULL;

SELECT ALL t1.c0, t1.c1, t5.c0, t5.c1 FROM t1 FULL OUTER JOIN t5* ON (('}n()')LIKE((((0.7999568)IS DISTINCT FROM(0.53532124)))::VARCHAR(100)));

### Operating System

ubuntu22

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

### PR DESCRIPTION
**Pull request by fanfuxiaoran**
For the below query

```
create table t1(a int, b int not null);
create table t2(like t1);
select t1.*, t2.* from t1 full join t2 on false where (t1.b < t1.b) is null;
```

orca generates a wrong plan:

```
Result  (cost=0.00..0.00 rows=0 width=16)
    One-Time Filter: false
Optimizer: Pivotal Optimizer (GPORCA)
```

The root cause is '(t1.b < t1.b)' is been transformed into 'CScalarConst (0)' by 'PexprEliminateSelfComparison'. The reason is that when checking if the `selfcomparison` can be simplified by function `FSelfComparison`, it checks the `CColRef` IsNullable only from the column definition, not checking if the column is from outer join.

To fix it, before simplifing the scalar expression, we fisrt get the 'pcrsNotNull' from its parent expression. 'pcrsNotNull' recoreds the output columns' nullable property. If the column is not in 'pcrsNotNull', then the self comparison cannot be transformed into const true or false.

Fixes #594 

### Type of Change
- [ ] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change)
- [ ] Breaking change (fix or feature with breaking changes)
- [ ] Documentation update

### Test Plan

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Passed `make installcheck`
- [ ] Passed `make -C src/test installcheck-cbdb-parallel`

### Impact

**Performance:**

**User-facing changes:**

**Dependencies:**

### Checklist
- [ ] Followed [contribution guide](https://cloudberry.apache.org/contribute/code)
- [ ] Added/updated documentation
- [ ] Reviewed code for security implications
- [ ] Requested review from [cloudberry committers](https://github.com/orgs/apache/teams/cloudberry-committers)

### Additional Context

⚠️ **To skip CI:** Add `[skip ci]` to your PR title. Only use when necessary! ⚠️

---

### CODE REVIEW

**Comment by fanfuxiaoran** [comment]
Working on adding tests for it!

**Comment by fanfuxiaoran** [comment]
Found that gpdb has a similar commit : https://github.com/greenplum-db/gpdb-archive/commit/d3dd98c1a8daf04fbf6cb91fc4afa6f91b317e93
Just cherry-pick it . 
But it has some problems, added a commit to fix it.

File: src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp [hunk 1]
```diff
@@ -70,16 +70,23 @@ using namespace gpopt;
...
 	GPOS_ASSERT(nullptr != pexpr);
+	COperator *pop = pexpr->Pop();
 
 	if (CUtils::FScalarCmp(pexpr))
 	{
-		return CPredicateUtils::PexprEliminateSelfComparison(mp, pexpr);
+		return CPredicateUtils::PexprEliminateSelfComparison(mp, pexpr,
+															 pcrsNotNull);
+	}
+	if (pop->FLogical())
```
Comment (jiaqizho) [inline src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp:87]:
```	
CExpression *pexprSelfCompEliminated = PexprEliminateSelfComparison(
		mp, pexprInferredPreds, pexprInferredPreds->DeriveNotNullColumns());
```
caller already call the `DeriveNotNullColumns`. why we need Derive it twice?

Comment (jiaqizho) [reply src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp:87]: The `Derive*` is not related to the CExpression type(logic/scalar/phy, also no phy CExpression will occar in the CExpressionPreprocessor) itself. 

So i guess the `CDrvdProp` always return true. when it check the `m_is_prop_derived`.

Comment (fanfuxiaoran) [reply src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp:87]: > ```
> CExpression *pexprSelfCompEliminated = PexprEliminateSelfComparison(
> 		mp, pexprInferredPreds, pexprInferredPreds->DeriveNotNullColumns());
> ```
> 
> caller already call the `DeriveNotNullColumns`. why we need Derive it twice?

'PexprEliminateSelfComparison' only uses the 'pcrsNotNull'
from the topmost expression to filter the nullable columns.
This can lead the PexprEliminateSelfComparison cannot apply
to the subquery properly.
```
create table t1(a int not null, b int not null);
create table t2(like t1);
create table t3(like t1);
select * from t2  left join (select  t2.a , t2.b  from t1, t2 where t1.a
	< t1.a) as t on t2. a = t.a;
```

the plan for it from orca is
```
 Gather Motion 3:1  (slice1; segments: 3)
   ->  Hash Left Join
         Hash Cond: (t2.a = t2_1.a)
         ->  Seq Scan on t2
         ->  Hash
               ->  Nested Loop
                     Join Filter: true
                     ->  Seq Scan on t2 t2_1
                     ->  Materialize
                           ->  Broadcast Motion 3:3  (slice2; segments: 3)
                                 ->  Seq Scan on t1
                                       Filter: (a < a)
```
the self comparison in subquery is not eliminated.

This commit is to optimize it by fetching 'pcrsNotNull' from
the current logical expression and apply them to its child
scalar expression.
The second commit is mainly to solve the above proble

Comment (jiaqizho) [reply src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp:87]: i see..

how about change the L98 ？
```
CExpression *pexprChild =
			PexprEliminateSelfComparison(mp, (*pexpr)[ul], (*pexpr)[ul]->DeriveNotNullColumns());
```

Comment (jiaqizho) [reply src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp:87]: i see. so can we just `} else if (pop->FLogical())` here? 

 `FScalarCmp` already check the CExpression is the `scalar` operator.

Comment (fanfuxiaoran) [reply src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp:87]: Sure. 
But in block `if (CUtils::FScalarCmp(pexpr))` , the function will return. 
Does `} else if (pop->FLogical())` help to understand the code?

Comment (fanfuxiaoran) [reply src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp:87]: Agree. And I will add the comments for it.

Comment (fanfuxiaoran) [reply src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp]: Fixed! And add regress test case for it

**Comment by fanfuxiaoran** [comment]
I'm supposed to add uttest for the new commit https://github.com/apache/cloudberry/pull/722/commits/ffb8b2e1e8141c43d38a0eac37b879af7b7c415b, but the uttests in the orca seem broken (before this pr) , some are failed, I need to to fix that first.   As that will take some time, so plan to create a issue for it and do it in a separate pr.

File: src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp [hunk 2]
```diff
@@ -84,7 +84,8 @@ CExpressionPreprocessor::PexprEliminateSelfComparison(CMemoryPool *mp,
 		return CPredicateUtils::PexprEliminateSelfComparison(mp, pexpr,
 															 pcrsNotNull);
 	}
-	if (pop->FLogical())
```
Comment (jiaqizho) [inline src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp]: squash the commit ffb8b2e1e8141c43d38a0eac37b879af7b7c415b to 4d2c7630bf5e06a783bc5b0ae67c9810c601784b pls. 

Current PR won't be squash when merged.

**Review by jiaqizho — APPROVED** [review]
LGTM

**Comment by my-ship-it** [comment]
fixes https://github.com/apache/cloudberry/issues/723

**Review by my-ship-it — APPROVED** [review]
