### PR TITLE
Fix: check and ereport error in external table

### LINKED ISSUE #1385: CREATE EXTERNAL TABLE with a non-existent EXECUTE command returns 0 rows instead of an error
When creating an external table using `CREATE EXTERNAL TABLE ... EXECUTE '...'`, if the specified command in the `EXECUTE` clause does not exist, Cloudberry returns 0 rows when the table is queried, without reporting any error. This behavior is inconsistent with Greenplum Database 7, which reports a clear error in the same scenario.

The silent failure in Cloudberry can be misleading for users, as it's impossible to distinguish between a command that successfully executed with no output and a command that failed to execute. The expected behavior is to propagate the error from the OS, informing the user that the command was not found.

```
cbdb@robertmu-VirtualBox:~$ psql
psql (14.4, server 14.4)
Type "help" for help.

cbdb=# CREATE EXTERNAL WEB TEMP TABLE test_program_exist(content text) EXECUTE 'seq 1 5' ON MASTER FORMAT 'TEXT';
CREATE EXTERNAL TABLE
cbdb=# select * from test_program_exist;
 content
---------
 1
 2
 3
 4
 5
(5 rows)

cbdb=# CREATE EXTERNAL WEB TEMP TABLE test_program_not_exist(content text) EXECUTE '/xx/seq 1 5' ON MASTER FORMAT 'TEXT';
CREATE EXTERNAL TABLE
cbdb=# select * from test_program_not_exist;
 content
---------
(0 rows)

cbdb=# select version();
                                                                                          version
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.4 (Apache Cloudberry 2.0.0-incubating-rc3 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit compiled on Aug 26 2025 10:53:40
(1 row)

cbdb=#
```

```
gpdb7@robertmu-VirtualBox:~$ psql
psql (12.12)
Type "help" for help.

gpdb7=# CREATE EXTERNAL WEB TEMP TABLE test_program_exist(content text) EXECUTE 'seq 1 5' ON MASTER FORMAT 'TEXT';
CREATE EXTERNAL TABLE
gpdb7=# select * from test_program_exist;
 content
---------
 1
 2
 3
 4
 5
(5 rows)

gpdb7=# CREATE EXTERNAL WEB TEMP TABLE test_program_not_exist(content text) EXECUTE '/xx/seq 1 5' ON MASTER FORMAT 'TEXT';
CREATE EXTERNAL TABLE
gpdb7=# select * from test_program_not_exist;
ERROR:  external table test_program_not_exist command ended with error. sh: /xx/seq: No such file or directory
DETAIL:  Command: execute:/xx/seq 1 5
gpdb7=#
gpdb7=# select version();
                                                                                                  version
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.0+482967c1b4 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit compiled on Nov  8 2024 23:43:47 Bhuvnesh C.
(1 row)

gpdb7=#
```

### PR DESCRIPTION
**Pull request by lss602726449**
In external table with CFTYPE_EXEC. We check stderr and ereport error when external_getnext return null.

Fixes #1385 

### Type of Change
- [ ] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change)
- [ ] Breaking change (fix or feature with breaking changes)
- [ ] Documentation update

### Test Plan

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Passed `make installcheck`
- [ ] Passed `make -C src/test installcheck-cbdb-parallel`

### Impact

**Performance:**

**User-facing changes:**

**Dependencies:**

### Checklist
- [ ] Followed [contribution guide](https://cloudberry.apache.org/contribute/code)
- [ ] Added/updated documentation
- [ ] Reviewed code for security implications
- [ ] Requested review from [cloudberry committers](https://github.com/orgs/apache/teams/cloudberry-committers)

### CI Skip Instructions

---

### CODE REVIEW

File: gpcontrib/gp_exttable_fdw/extaccess.c [hunk 1]
```diff
@@ -491,6 +491,24 @@ external_getnext_init(PlanState *state)
 	return desc;
 }
 
+static void
+check_error(FileScanDesc scan)
+{
+	char   *relname = pstrdup(RelationGetRelationName(scan->fs_rd));
+	int		ebuflen = 512;
+	char   *ebuf = palloc0(ebuflen);
```
Comment (my-ship-it) [inline gpcontrib/gp_exttable_fdw/extaccess.c]: better to use static char ebuf[512] here?

Comment (lss602726449) [reply gpcontrib/gp_exttable_fdw/extaccess.c]: Fixed.

Comment (gfphoenix78) [inline gpcontrib/gp_exttable_fdw/extaccess.c]: There is no need to allocate memory on the heap. `relname` is not owned by anyone. `ebuf` can use a stack array.

Comment (lss602726449) [reply gpcontrib/gp_exttable_fdw/extaccess.c]: Yes, pstrdup is unnecessary. I prefer palloc on heap than a stack array for 512 byte.

File: gpcontrib/gp_exttable_fdw/extaccess.c [hunk 2]
```diff
@@ -491,6 +491,24 @@ external_getnext_init(PlanState *state)
 	return desc;
 }
 
+static void
+check_error(FileScanDesc scan)
+{
+	char   *relname = RelationGetRelationName(scan->fs_rd);
+	int		ebuflen = 512;
+	char   *ebuf = palloc0(ebuflen);
```
Comment (gfphoenix78) [inline gpcontrib/gp_exttable_fdw/extaccess.c]: It's not a good idea here. The life cycle of the buffer is pretty short, and it's in the normal execute path. Finally, the memory of the buffer is leaked if error is not raised.

Comment (lss602726449) [reply gpcontrib/gp_exttable_fdw/extaccess.c]: You're right. fixed!

File: gpcontrib/gp_exttable_fdw/extaccess.c [hunk 3]
```diff
@@ -491,6 +491,24 @@ external_getnext_init(PlanState *state)
...
 
+static void
+check_error(FileScanDesc scan)
+{
+	char   *relname = RelationGetRelationName(scan->fs_rd);
+	int		ebuflen = 512;
+	char	ebuf[512] = {'\0'};
+
+	/* current only CFTYPE_EXEC will read stderr to ebuf */
+	url_ferror(scan->fs_file, -1, ebuf, ebuflen);
```
Comment (gfphoenix78) [inline gpcontrib/gp_exttable_fdw/extaccess.c]: Why is the returned value ignored? The existing code checks the returned value first, then the error buffer.
The `ebuf` could only initialize to an empty cstring, not necessarily all bytes.

Comment (lss602726449) [reply gpcontrib/gp_exttable_fdw/extaccess.c]: fixed!

**Review by gfphoenix78 — APPROVED** [review]
LGTM +1
