### PR TITLE
Fix CTAS crash.

### LINKED ISSUE #1218: [Bug] Create Table As crashed
### Apache Cloudberry version

main

### What happened

Image

### What you think should happen instead

_No response_

### How to reproduce

```sql
gpadmin=# create table t_random(id int) distributed randomly;
CREATE TABLE
gpadmin=# create table t_replicated as select random() from t_random distributed replicated;
FATAL:  Unexpected internal error (assert.c:48)
DETAIL:  FailedAssertion("!IsA(lefttree, Motion)", File: "createplan.c", Line: 7773)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
psql (14.4, server 14.4)

```

### Operating System

Ubuntu

### Anything else

_No response_

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/cloudberry/blob/main/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by avamingli**
Fix #1218 

If we create a replicated table when selecting project volatile functions from a randomly distributed table, we will try to add a Motion on a Motion node that will cause a crash. 

```sql
Create table t1(id int) distributed randomly;
Create table t2 as select random() from t1 distributed replicated;
```

planner may have add a top Motion earlier if we know the query's final locus. 
Some codes handle volatile functions lead us to create_motion_path_for_insert(), and we should consider the case to avoid Assertion failure when create_plan().

Authored-by: Zhang Mingli avamingli@gmail.com

Fixes #ISSUE_Number

### Type of Change
- [ ] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change)
- [ ] Breaking change (fix or feature with breaking changes)
- [ ] Documentation update

### Test Plan

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Passed `make installcheck`
- [ ] Passed `make -C src/test installcheck-cbdb-parallel`

### Impact

**Performance:**

**User-facing changes:**

**Dependencies:**

### Checklist
- [ ] Followed [contribution guide](https://cloudberry.apache.org/contribute/code)
- [ ] Added/updated documentation
- [ ] Reviewed code for security implications
- [ ] Requested review from [cloudberry committers](https://github.com/orgs/apache/teams/cloudberry-committers)

### CI Skip Instructions

---

### CODE REVIEW

File: src/backend/cdb/cdbpath.c [hunk 1]
```diff
@@ -2622,7 +2622,15 @@ create_motion_path_for_insert(PlannerInfo *root, GpPolicy *policy,
...
 		}
-		subpath = cdbpath_create_broadcast_motion_path(root, subpath, policy->numsegments);
+
+		/*
+		 * planner may have add a top Motion eariler.
+		 * Create table t1(id int) distributed randomly;
+		 * Create table t2 as select random() from t1 distributed replicated;
+		 * Avoid Motion if there was already one.
+		 */
+		if (!CdbPathLocus_IsReplicated(subpath->locus))
```
Comment (jiaqizho) [inline src/backend/cdb/cdbpath.c:2632]: How we make sure already have the broadcast motion in the subpath ?or when we added motion if current target table distributed by replicate?

File: src/test/regress/sql/bfv_planner.sql [hunk 2]
```diff
@@ -345,6 +345,9 @@ select count(*) from gp_dist_random('t_rep4');
 select count(distinct nextval) from gp_dist_random('t_rep4');
 drop table rep_tbl, t_rep4;
 
+create table t_issue_1218_random(id int) distributed randomly;
```
Comment (jiaqizho) [inline src/test/regress/sql/bfv_planner.sql:348]: add github issue url pls.

File: src/backend/cdb/cdbpath.c (hunk 1 above)
Comment (avamingli) [reply src/backend/cdb/cdbpath.c:2632]: Replicated is a Broadcast Motion.

Comment (jiaqizho) [reply src/backend/cdb/cdbpath.c:2632]: got

**Review by jiaqizho — APPROVED** [review]
LGTM
